group: Linux aarch64 tests
depends_on:
  - manylinux-aarch64
  - oss-ci-base_build-aarch64
  - forge-aarch64
steps:
  # block on premerge
  - block: "Run Linux aarch64 tests"
    if: build.env("BUILDKITE_PIPELINE_ID") == "0189942e-0876-4b8f-80a4-617f988ec59b"

  - label: ":ray: core: wheel-aarch64 tests"
    tags: linux_wheels
    instance_type: medium-arm64
    commands:
      - bazel run //ci/ray_ci:test_in_docker -- //python/ray/tests/... //doc/... core 
        --build-type wheel-aarch64
        --build-name oss-ci-base_build-aarch64
        --parallelism-per-worker 3
        --only-tags post_wheel_build
        --test-env=RAY_CI_POST_WHEEL_TESTS=True
    job_env: forge-aarch64

  - label: ":ray-serve: serve: wheel-aarch64 tests"
    tags: linux_wheels
    instance_type: medium-arm64
    commands:
      - bazel run //ci/ray_ci:test_in_docker -- //python/ray/serve/... //doc/... serve 
        --build-type wheel-aarch64
        --build-name oss-ci-base_build-aarch64
        --parallelism-per-worker 3
        --only-tags post_wheel_build
        --test-env=RAY_CI_POST_WHEEL_TESTS=True
    job_env: forge-aarch64
