group: Upload & Validate wheels
steps:
  - label: "MacOS x86_64"
    key: validate-macos-x86_64-wheels
    job_env: MACOS
    instance_type: macos
    commands:
      - ./.buildkite/release-automation/verify-macos-wheels.sh x86_64

  - label: "MacOS arm64"
    key: validate-macos-arm64-wheels
    job_env: MACOS
    instance_type: macos-arm64
    commands:
      - ./.buildkite/release-automation/verify-macos-wheels.sh arm64
